// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.ChessCloudCode
{
    public partial class BoardUpdateResponse
    {
        public string Board;
        public bool GameOver;
        public string EndgameType;

        [Preserve]
        public BoardUpdateResponse ()
        {
        }
    }
}