// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class ChessCloudCodeBindings
    {
        readonly ICloudCodeService k_Service;
        public ChessCloudCodeBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<ChessCloudCode.PlayerData> PrepareAndFetchPlayerData()
        {
            return await k_Service.CallModuleEndpointAsync<ChessCloudCode.PlayerData>(
                "ChessCloudCode",
                "PrepareAndFetchPlayerData",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<ChessCloudCode.InitializeMatchResponse> InitializeMatch(string sessionId)
        {
            return await k_Service.CallModuleEndpointAsync<ChessCloudCode.InitializeMatchResponse>(
                "ChessCloudCode",
                "InitializeMatch",
                new Dictionary<string, object>()
                {
                    {"sessionId", sessionId},
                });
        }

        public async Task<ChessCloudCode.HostGameResponse> HostGame()
        {
            return await k_Service.CallModuleEndpointAsync<ChessCloudCode.HostGameResponse>(
                "ChessCloudCode",
                "HostGame",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<ChessCloudCode.JoinGameResponse> JoinGame(string lobbyCode)
        {
            return await k_Service.CallModuleEndpointAsync<ChessCloudCode.JoinGameResponse>(
                "ChessCloudCode",
                "JoinGame",
                new Dictionary<string, object>()
                {
                    {"lobbyCode", lobbyCode},
                });
        }

        public async Task<ChessCloudCode.BoardUpdateResponse> MakeMove(string session, string fromPosition, string toPosition)
        {
            return await k_Service.CallModuleEndpointAsync<ChessCloudCode.BoardUpdateResponse>(
                "ChessCloudCode",
                "MakeMove",
                new Dictionary<string, object>()
                {
                    {"session", session},
                    {"fromPosition", fromPosition},
                    {"toPosition", toPosition},
                });
        }

        public async Task<ChessCloudCode.BoardUpdateResponse> Resign(string session)
        {
            return await k_Service.CallModuleEndpointAsync<ChessCloudCode.BoardUpdateResponse>(
                "ChessCloudCode",
                "Resign",
                new Dictionary<string, object>()
                {
                    {"session", session},
                });
        }
    }
}
