// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.ChessCloudCode
{
    public partial class JoinGameResponse
    {
        public string Session;
        public string Board;
        public string OpponentId;
        public bool IsWhite;

        [Preserve]
        public JoinGameResponse ()
        {
        }
    }
}