// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class ChessCloudCodeBindings
    {
        readonly ICloudCodeService k_Service;
        public ChessCloudCodeBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<ChessCloudCode.HostGameResponse> HostGame()
        {
            return await k_Service.CallModuleEndpointAsync<ChessCloudCode.HostGameResponse>(
                "ChessCloudCode",
                "HostGame",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<ChessCloudCode.JoinGameResponse> JoinGame(string lobbyCode)
        {
            return await k_Service.CallModuleEndpointAsync<ChessCloudCode.JoinGameResponse>(
                "ChessCloudCode",
                "JoinGame",
                new Dictionary<string, object>()
                {
                    {"lobbyCode", lobbyCode},
                });
        }

        public async Task<ChessCloudCode.BoardUpdateResponse> MakeMove(string session, string fromPosition, string toPosition)
        {
            return await k_Service.CallModuleEndpointAsync<ChessCloudCode.BoardUpdateResponse>(
                "ChessCloudCode",
                "MakeMove",
                new Dictionary<string, object>()
                {
                    {"session", session},
                    {"fromPosition", fromPosition},
                    {"toPosition", toPosition},
                });
        }

        public async Task<ChessCloudCode.BoardUpdateResponse> Resign(string session)
        {
            return await k_Service.CallModuleEndpointAsync<ChessCloudCode.BoardUpdateResponse>(
                "ChessCloudCode",
                "Resign",
                new Dictionary<string, object>()
                {
                    {"session", session},
                });
        }

        public async Task LeaveLobby(string lobbyId, string playerId)
        {
            await k_Service.CallModuleEndpointAsync(
                "ChessCloudCode",
                "LeaveLobby",
                new Dictionary<string, object>()
                {
                    {"lobbyId", lobbyId},
                    {"playerId", playerId},
                });
        }

        public async Task<Unity.Services.Leaderboards.Model.LeaderboardEntryWithUpdatedTime> AddPlayerScore(double score)
        {
            return await k_Service.CallModuleEndpointAsync<Unity.Services.Leaderboards.Model.LeaderboardEntryWithUpdatedTime>(
                "ChessCloudCode",
                "AddPlayerScore",
                new Dictionary<string, object>()
                {
                    {"score", score},
                });
        }
    }
}
