// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;

namespace Unity.Services.CloudCode.GeneratedBindings.ChessCloudCode
{
    public partial class InitializeMatchResponse
    {
        public string Status;

        [Preserve]
        public InitializeMatchResponse ()
        {
        }
    }
}