// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Unity.Services.Leaderboards.Model
{
    public partial class LeaderboardEntryWithUpdatedTime
    {
        public DateTime UpdatedTime;
        public string PlayerId;
        public string PlayerName;
        public int Rank;
        public double Score;
        public string Tier;

        [Preserve]
        public LeaderboardEntryWithUpdatedTime ()
        {
        }
    }
}